**주제**
프리미어리그 축구 데이터 분석

**프로젝트 이름**  프리미어리그 축구 분석

1.   승패 분석
2.   성적 분석

(1) 주제 선정 이유 : 축구에 관심을 가지고 있으면 팀들의 성적과 승패에 대해서 알아보고 싶어서다.

(2) 가설 정의: 

> 1. 내가 좋아하는 축구 클럽의 최근 성적을 불러온다.(우승 성적/ 현재 성적)



> 2. 우승성적과 현재 성적을 비교하며 부족한 부분에 대해 파악한다.



> 3. 비교해서 파악한 데이터를 가지고 축구 클럽의 문제점을 알아낸다.

(3) 인터넷을 통한 데이터 획득:

> 1. https://www.kaggle.com/datasets/irkaal/english-premier-league-results?resource=download 에서 최근 프리미어리그 성적을 파악한다.(result.csv 다운함)


> 2. 작동이 안될때 참조한 사이트들
  - https://wikidocs.net/book/1 에서 파이선에 대한 정보를 가지고 왔다.(문법)
  - Pandas : https://pandas.pydata.org/ <br> (pandas안될때)
  - matplotlib : 특정 사이트보단 구글링 하면서 크롤링하였다.

> 3. 모르거나 데이터가 막혀서 안되는 부분은 구글링 또는 사이트를 참조하였다.

(4) 분석을 위한 데이터의 가공: 최근 프리미어리그의 데이터를 모아놓은 csv를 pandas를 이용하여 데이터를 읽었다. 그리고 pandas를 통해서 홈팀과 어웨이팀의 승패를 보여주는 표를 출력하였다.

(자신이 고른 팀에 대한 성적 및 득점,실점 등 축구 데이터를 도식화 하여 표로 나타낼 것이다.) -> 아직 하지 못함.

In [10]:
#PL_result를 파일선택해 주세요!!
from google.colab import files
myfile = files.upload()

Saving PL_result.csv to PL_result (4).csv

In [39]:
import pandas as pd

data = pd.read_csv("PL_result.csv",encoding='windows-1254')

In [40]:
data.tail()

,Season,DateTime,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR
11108,2021-22,2022-04-09T17:30:00Z,Aston Villa,Tottenham,0,4,A,0.0,1.0,A,...,8.0,5.0,9.0,3.0,12.0,14.0,2.0,3.0,0.0,0.0
11109,2021-22,2022-04-10T14:00:00Z,Brentford,West Ham,2,0,H,0.0,0.0,D,...,7.0,1.0,4.0,6.0,2.0,6.0,0.0,1.0,0.0,0.0
11110,2021-22,2022-04-10T14:00:00Z,Leicester,Crystal Palace,2,1,H,2.0,0.0,H,...,3.0,3.0,3.0,4.0,11.0,12.0,1.0,1.0,0.0,0.0
11111,2021-22,2022-04-10T14:00:00Z,Norwich,Burnley,2,0,H,1.0,0.0,H,...,6.0,4.0,6.0,7.0,12.0,10.0,1.0,1.0,0.0,0.0
11112,2021-22,2022-04-10T16:30:00Z,Man City,Liverpool,2,2,D,2.0,1.0,H,...,5.0,4.0,4.0,1.0,9.0,11.0,1.0,4.0,0.0,0.0

In [57]:
#홈팀과 어웨이팀 이름 알려주는 것 (복사해서 붙여 넣어주세요)
a = 1
b = 0
Team_List = ["Liverpool","Arsenal","Coventry","Aston Villa","QPR","Chelsea","Blackburn","Sheffield Weds","Man City","Oldham","Sheffield United","Newcastle","Leeds","Southampton","Everton","West Ham","Wimbledon","Norwich","Man United","Tottenham","Ipswich","Swindon","Crystal Palace","Nott'm Forest","Leicester","Middlesbrough","Bolton","Derby","Sunderland","Barnsley","Charlton","Bradford","Watford","Fulham"]
for c in Team_List :
  print("(",a,")"," : ", Team_List[b])
  a = a+1
  b = b+1

print("_____________________________________________________________________________________________________")
print("주의 사항_1 : 만약 자신이 원하는 팀이 없을 경우 직접 검색해 영어로 넣어주세요.")
print("주의 사항_2 : 만약에 결과가 안나올 경우 당황하지 마시고 csv파일에 있는 이름을 붙여 넣어주세요.")

( 1 )  :  Liverpool
( 2 )  :  Arsenal
( 3 )  :  Coventry
( 4 )  :  Aston Villa
( 5 )  :  QPR
( 6 )  :  Chelsea
( 7 )  :  Blackburn
( 8 )  :  Sheffield Weds
( 9 )  :  Man City
( 10 )  :  Oldham
( 11 )  :  Sheffield United
( 12 )  :  Newcastle
( 13 )  :  Leeds
( 14 )  :  Southampton
( 15 )  :  Everton
( 16 )  :  West Ham
( 17 )  :  Wimbledon
( 18 )  :  Norwich
( 19 )  :  Man United
( 20 )  :  Tottenham
( 21 )  :  Ipswich
( 22 )  :  Swindon
( 23 )  :  Crystal Palace
( 24 )  :  Nott'm Forest
( 25 )  :  Leicester
( 26 )  :  Middlesbrough
( 27 )  :  Bolton
( 28 )  :  Derby
( 29 )  :  Sunderland
( 30 )  :  Barnsley
( 31 )  :  Charlton
( 32 )  :  Bradford
( 33 )  :  Watford
( 34 )  :  Fulham
_____________________________________________________________________________________________________
주의 사항_1 : 만약 자신이 원하는 팀이 없을 경우 직접 검색해 영어로 넣어주세요.
주의 사항_2 : 만약에 결과가 안나올 경우 당황하지 마시고 csv파일에 있는 이름을 붙여 넣어주세요.

In [55]:
# 홈팀과 어웨이팀의 승패 (*위의 팀 알림이에서 복사해서 붙여 넣어주세요*)
home_Team = input("Home Team : ")
away_Team = input("Away Team : ")
print("Selected team(Home : Away) : " + home_Team + " : " + away_Team)

preResult = pd.concat([data[data['HomeTeam']==home_Team], data[data['AwayTeam']==home_Team]]).sort_index()
result = pd.concat([preResult[preResult['AwayTeam']==away_Team]]).sort_index()
result

Home Team : Fulham
Away Team : Man City
Selected team(Home : Away) : Fulham : Man City

,Season,DateTime,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR
3787,2002-03,2002-12-28T00:00:00Z,Fulham,Man City,0,1,A,0.0,0.0,D,...,7.0,8.0,4.0,13.0,7.0,14.0,0.0,1.0,0.0,0.0
4013,2003-04,2003-09-20T00:00:00Z,Fulham,Man City,2,2,D,0.0,0.0,D,...,9.0,6.0,2.0,4.0,14.0,19.0,2.0,5.0,0.0,0.0
4666,2004-05,2005-04-16T00:00:00Z,Fulham,Man City,1,1,D,0.0,1.0,A,...,3.0,3.0,6.0,8.0,9.0,19.0,0.0,1.0,0.0,0.0
4833,2005-06,2005-11-05T00:00:00Z,Fulham,Man City,2,1,H,2.0,1.0,H,...,5.0,2.0,4.0,2.0,10.0,16.0,1.0,3.0,0.0,0.0
5426,2006-07,2007-04-09T00:00:00Z,Fulham,Man City,1,3,A,0.0,2.0,A,...,5.0,5.0,7.0,4.0,12.0,15.0,1.0,3.0,0.0,0.0
5542,2007-08,2007-09-22T00:00:00Z,Fulham,Man City,3,3,D,1.0,1.0,D,...,8.0,5.0,6.0,2.0,10.0,7.0,3.0,2.0,0.0,0.0
6016,2008-09,2008-12-06T00:00:00Z,Fulham,Man City,1,1,D,1.0,1.0,D,...,8.0,7.0,9.0,7.0,6.0,5.0,2.0,1.0,0.0,0.0
6544,2009-10,2010-03-21T00:00:00Z,Fulham,Man City,1,2,A,0.0,2.0,A,...,4.0,9.0,4.0,2.0,8.0,9.0,0.0,0.0,0.0,0.0
6762,2010-11,2010-11-21T00:00:00Z,Fulham,Man City,1,4,A,0.0,3.0,A,...,3.0,8.0,7.0,7.0,13.0,16.0,2.0,1.0,0.0,0.0
7049,2011-12,2011-09-18T00:00:00Z,Fulham,Man City,2,2,D,0.0,1.0,A,...,11.0,11.0,6.0,9.0,10.0,9.0,1.0,1.0,0.0,0.0
7435,2012-13,2012-09-29T00:00:00Z,Fulham,Man City,1,2,A,1.0,1.0,D,...,3.0,12.0,2.0,4.0,7.0,12.0,0.0,1.0,0.0,0.0
7925,2013-14,2013-12-21T00:00:00Z,Fulham,Man City,2,4,A,0.0,2.0,A,...,5.0,10.0,4.0,4.0,7.0,15.0,1.0,1.0,0.0,0.0
9971,2018-19,2019-03-30T00:00:00Z,Fulham,Man City,0,2,A,0.0,2.0,A,...,0.0,7.0,0.0,11.0,4.0,12.0,2.0,0.0,0.0,0.0
10704,2020-21,2021-03-13T20:00:00Z,Fulham,Man City,0,3,A,0.0,0.0,D,...,0.0,7.0,4.0,2.0,14.0,13.0,0.0,0.0,0.0,0.0

프로그램 제작중...